coins:
  #- exchange: bybit
  #  symbol: BTCUSD
  #- exchange: ftx
  #  symbol: BTC-PERP
  #- exchange: ftx
  #  symbol: BTC/USD
  #- exchange: gmo
  #  symbol: BTC_JPY
  #- exchange: liquid
  #  symbol: BTC_JPY
  #- exchange: bitflyer
  #  symbol: FX_BTC_JPY
  
  # bitbank
  - exchange: bitbank
    symbol: btc_jpy
  #- exchange: bitbank
  #  symbol: eth_jpy
  #- exchange: bitbank
  #  symbol: xrp_jpy
